### ISSUE TITLE
HTTPS interception

### ISSUE THREAD

**Issue by vidarak** [nodogsplash/nodogsplash#3] opened 2013-06-16 23:44 UTC
Hi
Is it possible to get nodogsplash to intercept HTTPS requests also?

Rgds,
Vidar

**Comment by lynxis** [comment] 2015-05-11 09:59
I don't like this functionality in nodogsplash, because it requires https:// breakage. Most modern OS now honor captive portal via http:// checks against known URL and notify the user.
However I think it's a good idea to document https:// support without changing nodogsplash.

**Comment by vidarak** [comment] 2015-05-11 10:24
lynxis,
This is about user experience really. All major commercial proxy services and captive portals do HTTPS interception for good reasons. Sure, it breaks the HTTPS while at the captive portal page, but that's better than getting an error message indicating there is no connectivity while the user is waiting for OS to detect the captive portal.

**Comment by lynxis** [comment] 2015-05-11 14:24
@vidarak I still don't like the idea of https:// redirecting, but maybe somebody would like to enable.
With Strict-Transport-Security this thing got even worse and I would say a Chrome run amok when it sees such certificates for google.com. No idea how other browser behave. Also this would teach users to ignore every BIG FAT WARNING about don't do this.

**Comment by Kafeine341** [comment] 2015-07-30 10:17
Hey ! 
I'am trying to put in practice the solution of @epipenau & @albig but i have a infinite loading on HTTPS pages.
My goal is to redirect users to the login page of NoDogSplash when they try to load a HTTPS page before auth. 
I added in location http://redirect.fr (dumb domain) so the page of NoDogSplash come.
*Thanks for any help*

1/ Did i need to generate the crt files you use in the config ? 
those : 
option cert '/etc/uhttpd.crt'
option key '/etc/uhttpd.key'

2/ Is this config right ? I tried to add the additional \r\n" at the end of the line

*/etc/config/nossl.lua*
```
function handle_request(env)
uhttpd.send("Status: 302 Found\r\n")
uhttpd.send("Location: http://redirect.fr:80/\r\n")
uhttpd.send("Connection: close\r\n")\r\n
end
```

**Comment by thxred** [comment] 2015-09-01 21:42
I have the same problem as Daemon024, also tried change from "uhttpd.send("Location: http://IP:80/\r\n")r\n" to ""uhttpd.send("Location: http://IP:80/\r\n\r\n")" but does not redirect.

Thanks

**Comment by cloudstm** [comment] 2015-09-17 13:09
Hi Guys,
someone could fix this?
Because in Brazil the home page usually is google.com.

**Comment by joernroeder** [comment] 2015-11-10 20:21
more and more sites are using https by default (which is awesome) and redirecting https clients as well (maybe downgrade and redirect them to the http://splashpage) should be implemented. Otherwise the splashpage won't show up as a lot of users uses a https://favorite-search-engine as their start page.

**Comment by ArtMartin89** [comment] 2015-11-17 19:12
Hello everyone, can somebody tell how to solve https problem with NDS? I've read previous posts & don't understand if someone have solved it for sure. I've tried what @gluedig and @sayuan suggest, but haven't got the result. Maybe I do something wrong, I'm not as experienced as you guys, so if there is a solution for this problem can someone tell the step-by-step instruction.

**Comment by haircrime** [comment] 2016-08-16 15:01
Hi guys,

As ArtMartin89 is already asking, I am trying to revive this thread one more time.

Does anyone have any recommendations how to get nodogsplash to forward to the splash page, when a https request was made by the user.

Anything I can try out, even if it has the obious drawbacks of breaking the SSL etc...

Thank you very much, this would be a great help.

**Comment by mwarning** [comment] 2016-08-16 19:22
@haircrime well, someone has to implement something. :-)

**Comment by bluewavenet** [comment] 2016-08-16 20:23
It would be nice but the question is - Is it worth the effort?
100% of smartphone and tablet devices (iOS, Android and Windows) use their built in Portal Detection procedure. This tries to access some pre defined web page via http on port 80, not a browser home page, so works just fine with Nodogsplash.
In my experience of public hotspots, nearly 100% of devices are smartphones or tablets. Searching logs of a busy site shows less than 1 in 1000 devices are not this type. ie a very occasional Apple or Windows laptop (and a growing minority of Linux laptops!).
True that my logs would not show rejected devices trying https as a home page, but I think these will be rare.

**Comment by haircrime** [comment] 2016-08-16 21:17
@bluewavenet

Hi, yes you certainly have a point. And until a couple of weeks ago, you were right.

Lately I have received a lot more complaints about not working hotspot connections. By doing some research I discovered that some newer Samsung mobile phones, running Android launch the browser with HTTPS://Google.com , when detecting a captive portal.

I have no idea why in the world Samsung would change the normal Android behavior, but of course this leads to a time out on nodogsplash.

**Comment by bluewavenet** [comment] 2016-08-16 23:12
I have just tried on a Samsung phone with the very latest updates and see the following:
User Agent: Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-G900F/G900FXXS1CPG2 Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36

Requested URL: http://www.google.com/

Can you capture the user agent string from one of the problem devices?

**Comment by bluewavenet** [comment] 2016-08-16 23:39
@haircrime 
How do you know they request https://google.com?
In my example:
If the device was to connect to an open wifi that was not a redirecting hotspot like Nodogsplash, the Portal Detection will try to access http://google.com and, as it has immediate access to the Internet, will be redirected  by Google to https://google.com so you may not actually be seeng Samsung doing something odd.

**Comment by bluewavenet** [comment] 2016-08-16 23:48
@haircrime 
Could you be seeing a manifestation of  #113 ?

**Comment by haircrime** [comment] 2016-08-17 13:43
@bluewavenet 

thank you for your input and I have checked #113 but this is not the cause.

Attached you can find screenshots of 2 samsung phones I can replicate this issue with.


![1](https://cloud.githubusercontent.com/assets/11500581/17737961/a17cc48c-648f-11e6-8e1f-7946c8c23488.png)

After selecting the free hotspot that runs nodogsplash, the android notification asks the user to sign in. After clicking, the regular browser opens.


![2](https://cloud.githubusercontent.com/assets/11500581/17737960/a174e0be-648f-11e6-8c2b-823311a8a0ec.png)

The browser tried to load https://google.com and times out. There is no way for the user to get to the redirect page, unless he enters by hand a non-ssl url - which is rare.

What I normally find on android phones is, that after clicking the captive portal notification, a webview popup browser will open. This browser has limited feates (no javascript, no cookies etc..) and it loads a normal "non-ssl" url (gstatic...) which will result in a redirect to the nodogsplash landing page. So this behaviour is great and easy to use. Why does Samsung change the Android behaviour?


Does nobody else experience similar effect?
bluewavenet, any ideas?

Thanks a lot...



Infos about the phones:
![1stphone_1](https://cloud.githubusercontent.com/assets/11500581/17738124/49db7056-6490-11e6-9c9a-eb3c5bf86a6b.png)
![1nd phone_2](https://cloud.githubusercontent.com/assets/11500581/17738126/4c67f2cc-6490-11e6-8eb3-b71df428badb.png)
![2ndphone_1](https://cloud.githubusercontent.com/assets/11500581/17738127/4ea87fe8-6490-11e6-9eb8-b5ce39279ea5.png)
![2ndphone_2](https://cloud.githubusercontent.com/assets/11500581/17738131/51ddaeb8-6490-11e6-923a-c1577ab3a3d5.png)

**Comment by bluewavenet** [comment] 2016-08-18 12:42
I have access to three Samsung phones at the moment running various versions of Android ranging from before your examples to versions after. All work normally and also I have not received any complaints from potential users. 
As you have the apparent problem with various versions of Android on these Samsung devices, it looks like the problem lies elsewhere and is quite intriguing! 
The url used for the portal detection is held in a configuration file only accessible on routed Android devices and is of the form:
[http://connectivitycheck.gstatic.com/generate_204](url)
[http://clients3.google.com/generate_204](url)
etc. with variations depending upon vendor.
However recent versions (since around mid 2015) have been delivered with just plain old [http://google.com](url)

It is possible (on routed devices) to disable Portal detection entirely.
Also, manual opening of a browser will attempt to go to the home page whatever it is.

Other operating system vendors have their own versions eg.:
[http://captive.apple.com/hotspot-detect.html](url)
[http://www.windowsphone.com/](url)

Changing the url to https will break Portal Detection. Samsung would not (intentionally) do this and I cannot see any other evidence that they have done so.

So what is causing your problem?

For example - on my laptop computer, if I connect to a Nodogsplash hotspot, start Firefox and click my bookmark for [http://google.com](url) I get the splash page.

If I do not use the laptop for a while and the Nodogsplash idle timeout is exceeded but Firefox is still running and I click the bookmark, I find Firefox has cached the Google redirect to https and of course I will not get the splash page. 

Is perhaps something like this happening?

**Comment by vidarak** [comment] 2016-08-18 12:51
I think it might boil down to which browser is the default browser on the phone and what web page is the startup/home page in the browser?

Scenario:
1. phone connects to wifi
2. phone checks one of those URLs you mention (http://clients3.google.com/generate_204) and discovers it cannot reach it so it notifies user about captive portal / sign in requirement
3. user clicks the notification which opens the default browser
4. default browser goes to its startup page... which is https://www.google.com and THAT doesn't work.

**Comment by bluewavenet** [comment] 2016-08-18 13:18
Yes @vidarak !
The Portal detection should open the browser automatically and pass the detection url to it.
It should be independent of the default browser. For example on my personal phone with either the Samsung Internet app or Firefox for Android it goes to [http://google.com](url) regardless of the home page setting of the browser.
In fact the Portal detection tries the detection url directly without using the browser and should only start the browser if it does not receive the expected answer ie a 204 response. The browser is invoked with the detection url in its command line thus overriding the home page setting. At least this is how it is "supposed" to work. This is the first time I have heard of a browser that ignores this and goes to its home page regardless. Unfortunately I cannot replicate this problem.

**Comment by vidarak** [comment] 2016-08-18 13:24
I'm not so sure the browser is supposed have the detection URL passed to it. That would be very counter-intuitive as the response from the detection URL is a "204" text response.  I think you got that part wrong...
I don't question the fact that the OS is using the detection URL outside of the browser - for the detection. It's just not passing that URL to the browser (and it is not supposed to!). Perhaps some phones have been hard-coded to pass a different URL (like http://google.com), but that is outside any standards AFAIK.

**Comment by haircrime** [comment] 2016-08-18 13:45
Hi Guys,
thank you for the input.

There are so many different scenarios and interpretations of the operating systems that it is difficult to keep track of.

In general you guys are right: the captive portal detection of the operating system should open some sort of browser and forward to the login page.

Just in case the error reported by my users and my replication is correct and will be found on more devices in the future, do you guys think there is any realistic approach to develop some sort of "enhancement" for nodogsplash to deal with this? In what direction would you look?

**Comment by bluewavenet** [comment] 2016-08-18 13:49
It does pass the detection url as this is the only way to guarantee a non-https url - and I get the same url passed to the splash page by Nodogsplash regardless of the browser used. Some time ago I experimented with a rooted Android and could make it try anything I liked and all Android browsers I could find worked in the same way. The latest incarnations of the Portal Detection seem to send a specific html POST to google.com and expect the 204 response as that web site is now set up to respond in this way. I have been meaning to do a trace to confirm the details of this. It is true there is no vendor independent standard for this but all vendors seem to have followed the Google lead on this.

**Comment by vidarak** [comment] 2016-08-18 13:49
I can add that for my project @work we had to abandon the idea of using nodogsplash. We went with Mikrotik RouterOS on virtual machines or on dedicated RouterBoards.

**Comment by vidarak** [comment] 2016-08-18 13:53
I just tested on a Win10 VM placed behind captive portal and it consistently opens a/any browser with the URL "http://go.microsoft.com/fwlink/?LinkID=219472&clcid=0x409" when detecting captive portal - shortly after login.

**Comment by bluewavenet** [comment] 2016-08-18 13:54
@vidarak - It all depends on what you are trying to achieve. As I said earlier:
It would be nice but the question is - Is it worth the effort?
100% of smartphone and tablet devices (iOS, Android and Windows) use their built in Portal Detection procedure. This tries to access some pre defined web page via http on port 80, not a browser home page, so works just fine with Nodogsplash.
In my experience of public hotspots, nearly 100% of devices are smartphones or tablets. Searching logs of a busy site shows less than 1 in 1000 devices are not this type. ie a very occasional Apple or Windows laptop (and a growing minority of Linux laptops!).
True that my logs would not show rejected devices trying https as a home page, but I think these will be rare.

**Comment by vidarak** [comment] 2016-08-18 13:56
You also have to think about the situation where users ignore the notification and just open the browser, expecting to get captive portal..... but don't - because their startup page in the browser is HTTPS.

**Comment by bluewavenet** [comment] 2016-08-18 14:28
The notification clearly says authentication is required and if they choose to ignore it ....
As I said, it would be nice, but is it worth it for a tiny minority? 

It is a tiny minority for public hotspots and I have not had any feedback to indicate it is a problem and this is over a number of very busy sites.

As you have found out for yourself, even Windows 10 now supports Captive Portal Detection using http.

**Comment by haircrime** [comment] 2016-08-18 14:50
OK understood.

When you say: is it really worth it for a tiny minority, it sounds like you know it will be a lot of effort to develop.

Maybe it's an easy fix, which would make nodogsplash even better ;)

**Comment by bluewavenet** [comment] 2016-08-18 14:56
It might be easy, I have not thought about it other than thinking it will encourage bad practice in ignoring certificate errors.
Someone would have to do it, that is the only problem I suspect.
any volunteers? ;)

**Comment by haircrime** [comment] 2016-08-18 15:40
I volunteer to help and test ;-)

**Comment by bluewavenet** [comment] 2016-08-19 14:27
I spent a couple of happy hours this morning with Wireshark, Gnome Desktop with Network Manager Connectivity Check (Captive Portal Detection), and a Samsung GS5 with the latest version of Android.
The Network Manager Connectivity Check is open source and seems to becoming a standard. 
The Wireshark output for this and for the Android device  seems identical apart from the $redirect sent to Nodogsplash. Network Manager is hardwired (on my Gnome Desktop) to try http://www.gnome.org whereas Android 6.01 seems to be hardwired to http://google.com
Both try the configured uri for a total of 3 tries on failure (ie in the walled garden of NodogSplash) before finally opening a browser (the default on Android or a built in mini-browser on Gnome) with the hardwired http:// url.
It seems to me that Google are now using the Network Manager code in Android (from version 6.0 onwards?) with http://google.com hardwired.

Now @haircrime , I can replicate a similar problem to yours on my Gnome desktop. If Firefox is running and has previously been to http://google.com, it will have been redirected by Google to https://google.com
If my Nodog Token has expired, yet Firefox is still running AND I do not log in with the built in mini-browser THEN try access to http://google.com on Firefox, it actually immediately tries https://google.com as this is in the Firefox cache - resulting in a timeout as NodogSplash ignores me!
If Network Manager on Gnome was to finally try http://google.com with Firefox, I would have exactly the problem you described.
So I tried just this on the Samsung with Firefox for Android as the default. Result - timeout.
However if I had not accessed Google it worked perfectly.
In the non-working state, powering off and on the Samsung also fixed the problem.
So did terminating Firefox and restarting it.
And finally, telling Android to forget the Wifi SSID then reconnecting fixed the problem too.

A conclusion to all this is that the issue is caused by browser caching of Google's own redirect. 
Any thoughts anyone?

**Comment by mwarning** [comment] 2016-08-23 20:45
fwiw, the nodogsplash code in trunk (aka 2.0) uses libmicrohttpd, which has support for https. So it is possbile to let nodogsplash serve via https. I don't think it will work out of the box.

**Comment by agustindev** [comment] 2016-09-12 14:28
Can't we add an iptable rule to redirect all 443 port request to 80 on ndsOUT (without exception) as an init.d appart of nds, and let exceptions from nds.conf on other ports. 

Im adding exceptions for facebook ipset in a custom init.d and it works.
/usr/sbin/iptables -t nat -I ndsOUT 6 -m set --match-set facebookset dst -j ACCEPT
/usr/sbin/iptables -I ndsNET 9 -m set --match-set facebookset dst -j ACCEPT

Im new with iptables..

**Comment by agustindev** [comment] 2016-09-12 15:16
Hey people! I found this 
https://www.chromium.org/chromium-os/chromiumos-design-docs/network-portal-detection

**Comment by bluewavenet** [comment] 2016-09-12 16:09
@agustindev - yes - your link is quite old now but gives an idea of the basics.
My argument above was that redirection of https for a Hotspot in public use is not required as Portal Redirection is now standard in all mobile devices and in all up to date desktops and it does its own port 80 http test. The set up of the router running NDS should be already setting the DNS server of clients via DHCP. I am not sure why you would want to make NDS change it again.

**Comment by bluewavenet** [comment] 2016-09-12 16:20
This link will also give you some insight into Captive Portal detection: [https://progress.opensuse.org/issues/9450](url)

**Comment by haircrime** [comment] 2016-09-14 09:54
@agustindev 

..did you make it work with ipsets or iptable?

@bluewavenet

I agree with you, that most mobile device behave correct and open the captive portal with the login page.

But I still have the issues with the devices that do not do this. If NDS would redirect https://google.com - would be a great help.

So if anyone comes across an idea - I will be happy to try it.

Thanks...

**Comment by agustindev** [comment] 2016-09-15 00:17
@haircrime I did it for whitelisting no blacklist. 
@bluewavenet

When I run https google into chrome, and wait every packet timeout, the browser makes an http request and open another page with the portal.

What about dropping all google.com dst ipset  packets to force the browser makes this request??
Ill wireshark it..

@haircrime idea about redirect could be an option 

Thanks

**Comment by agustindev** [comment] 2016-09-15 00:52
@haircrime @bluewavenet somthing like this https://github.com/wifidog/wifidog-gateway/issues/6

If nds is based on wifidog and this issue is closed, I think it could work

**Comment by xewonder** [comment] 2016-09-27 08:04
Hi,

I am a bit late with this, but have you found a solution for Samsung phones?

https://drive.google.com/file/d/0B0tIo4L0lOvqS2FVLVUxNzVfVVU/view?usp=sharing

Reading about it, it has nothing to do with DNS but what the site "throws" at the browser.


QUOTE from WIKI (https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security)

HTTP Strict Transport Security (HSTS) is a web security policy mechanism which helps to protect websites against protocol downgrade attacks and cookie hijacking. It allows web servers to declare that web browsers (or other complying user agents) should only interact with it using secure HTTPS connections,[1] and never via the insecure HTTP protocol. HSTS is an IETF standards track protocol and is specified in RFC 6797.

UNQUOTE


So the samsung phones/tables redirect to www.google.com and Chrome converts to https!

**Comment by bluewavenet** [comment] 2016-09-27 13:23
I have tested extensively now with Samsung and cannot replicate the error, but have not tried with Chrome as in your video. If you make the Samsung browser the default again (as it will be on the phone initially) then it will work, as indeed it will with Firefox. It seems it is the Chrome browser that breaks CPD.
Also read issue #140 for more insights into this.

**Comment by xewonder** [comment] 2016-09-27 14:26
Thanks.

If you see the video, Firefox has no problem.

I guess users (I have about 400 routers out there) with Samsung and Chrome 
as their default browser will not be able to get the splash page. Adding 
.google.com to the whitest is not an option.. I think


------------------
Best regards
Denis Dorigo

(sent from mobile device)

**Comment by bluewavenet** [comment] 2016-09-27 16:34
Yes, works fine with both Samsung browser and Firefox. The CPD on Android seems to invoke the default browser. 
If this can be verified as a problem with Chrome browser it should be reported as a bug to Google.
https://support.google.com/chrome/answer/95315

**Comment by bluewavenet** [comment] 2016-09-27 16:52
I do however think something else is going wrong somewhere.
The Android CPD normally uses http://connectivitycheck.gstatic.com/generate_204 regardless of the browser in use.

**Comment by xewonder** [comment] 2016-09-27 17:10
@bluewavenet  Thak you for replies.

The more I look at this the more the more I am sure it is a SAMSUNG - CHROME problem. But finally Chrome!

I have now tested with serveral android devices and:

1> Samsung "log on to WIFI" pushes www.google.com. 
2> Chrome (on any tested andorid device) converts www.google.com to https://... even before coova or anything else can intercept the request. Other browsers show http splash!

This comes down to a "too stric" implementation  of HSTS by Chrome.

By the looks of it, HSTS pushes someting to the browser telling it that "next time" it should use HTTPS to reach the address... 

QUOTE from https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security

HSTS mechanism overview

A server implements an HSTS policy by supplying a header over an HTTPS connection (HSTS headers over HTTP are ignored).[12] For example, a server could send a header such that future requests to the domain for the next year (max-age is specified in seconds; 31,536,000 is equal to one non-leap year) use only HTTPS: Strict-Transport-Security: max-age=31536000.

When a web application[13] issues HSTS Policy to user agents, conformant user agents behave as follows:[14]

    Automatically turn any insecure links referencing the web application into secure links. (For instance, http://example.com/some/page/ will be modified to https://example.com/some/page/ before accessing the server.)
    If the security of the connection cannot be ensured (e.g. the server's TLS certificate is not trusted), show an error message and do not allow the user to access the web application.[15]

The HSTS Policy helps protect web application users against some passive (eavesdropping) and active network attacks.[16] A man-in-the-middle attacker has a greatly reduced ability to intercept requests and responses between a user and a web application server while the user's browser has HSTS Policy in effect for that web application.

UNQUOTE

So YES! this should (and I will) be reported to google and also Samsung!!

I have the feeling that this can not be overcome without them!

**Comment by bluewavenet** [comment] 2016-09-27 17:28
Any CPD should try its tests on the network directly and not via a browser. If detection of the captive portal is positive then the browser should be invoked, passing a URL to the browser on the command line. I suspect Chrome is ignoring this and trying https://google.com instead. I will try a few more tests.

**Comment by bluewavenet** [comment] 2016-09-27 17:36
I have just installed Chrome on a SG5 and made it the default and can now replicate the error. Chrome when invoked immediately tries https://google.com
It still works in Firefox and Samsung browsers.

**Comment by xewonder** [comment] 2016-09-27 18:21
@bluewavenet 

unless you clear the cache... then it woks a few times.. my guess is unill you visit www.google.com and then it downloads that "stupid" HSTS file....

**Comment by bluewavenet** [comment] 2016-09-27 18:28
It was a fresh, first time install of Chrome that I tried and it failed at the first attempt so I am not sure what is happening, however you seem to be on the right track ;)

**Comment by bluewavenet** [comment] 2016-09-27 18:46
Looking closely at a few more tests:
Android 6.0 tries http://connectivitycheck.gstatic.com/generate_204 and passes the same to the browser.
Android 6.01 tries http://connectivitycheck.gstatic.com/generate_204 but passes http://www.google.com.
So it seems a combination of Android 6.01 CPD and Chrome over "strict" might be causing the problem - but not necessarily as on a number of large sites I have not received any complaints of this problem. The latest version of Chrome perhaps?

**Comment by bluewavenet** [comment] 2016-09-27 18:59
http://google.com does a 302 redirect to https://www.google.com
This would be ok and would work in NDS as the initial request is http.
Yet Chrome goes directly to https
My conclusion is that it is definitely Chrome causing the problem with a built in redirect rather than letting the web site do it.

**Comment by xewonder** [comment] 2016-09-27 19:11
just as a"cherry on the cake".

I have tested on a device that is not even online (wifi off and sim card out).

Chrome transforms www.google.com (that I typed in) to https://www.google.com!!

**Comment by wificatalogue** [comment] 2016-10-11 07:17
Hi, i have been researching the same issue for the last couple of weeks because i am facing customers complains too. I have reached the same conclusion. The latest version of Chrome when is the default browser,  messes up the captive portals because of the HSTS implementation only on android lollipop. 

We need to open a ticket somewhere and get a response from them.

**Comment by pmosse** [comment] 2016-10-21 15:44
Hello everyone! I am facing the same problem. The captive is displayed in some phones (Samsung J1) as https://www.google.com, then the customer navigates freely to some HTTPS sites (like Facebook) and after a little while they are kicked out of the connection as the phone thinks there is no internet...

**Comment by bluewavenet** [comment] 2016-10-22 13:04
I have just checked the logs of an extremely busy hotspot I have installed. In over 2500 logins, some 200 or so were using Chrome 55.0.2883, at the time of writing, the current release version I think.
At that site there have been no complaints received.
 
https will not bring up the splash page in any circumstances as Captive Portal Detection (lets call it CPD) as it is designed to use its own http port 80 request.

On Linux CPD is built into Networkmanager. Different distributions use their own url but all of them are designed to return 204 "no content" return code or a pre defined response string. This signals to the CPD that a valid Internet connection is present. If the CPD receives anything other than 204 or the response string with a 304 (see below) it will assume a splash page, if it receives nothing it will assume no connection to the internet. All this is done on port 80.

The configuration is in the NetworkManager.conf file, found usually in /etc/networkmanager or thereabouts.
It will be in the [connectivity] section.

in OpenSuse Leap it is:
[connectivity]
uri=http://conncheck.opensuse.org
response=NetworkManager is online
interval=300

In Debian it is:
[connectivity]
uri=http://network-test.debian.org/nm
response=NetworkManager is online
interval=300

On Android and iOS it is similar, but you have to root the device to see the details.

Note the interval defaults to 300 seconds. On first connecting to the WiFi the CPD will try the configured URL. Then it will retry at 300 second intervals.

What some people may be seeing is the following sequence:
1. You are already connected to the Wifi but not logged in
2. You open your browser and try an https site.
3. NodogSplash ignores you
4. The timing interval expires and the CPD kicks in, receives something other than 204 from NDS and pops up its browser to display the NDS splash page.
Obviously this can take up to 5 minutes (300 seconds) with the default NetworkManager config.

Also if you are using the version distributed with Barrier Breaker (0.9_beta9.9.8-1), it is broken and lets everything through except port 80. @pmosse - the symptom of this is as you describe here.

I have now tried again, testing with Chrome 55.0.2883 and can only replicate using the scenario I describe here. This actually happens with ANY browser.

**Comment by pmosse** [comment] 2016-10-24 02:27
Hey @bluewavenet, thanks for the full explanation! Yes, it is as you say. I am actually using the version 1.0... Do you think there is any way to display the Splash for the users that have an HTTPS site as the default (or maybe they don't but Google is displayed anyway)? Maybe playing with the DNS servers and changing Google's IPs to something else? Or intercepting the requests at some level?

**Comment by bluewavenet** [comment] 2016-10-24 07:47
The point here is that even with a home page set up for https, the CPD will still always use its own port 80 request. 
For a public hotspot I am seeing less than 1 in 2000 devices that are not CPD enabled. These are the very few old Windows laptops running Vista or earlier. 
If you can replicate the issue on a Samsing smart phone for example. Try disconnecting the wifi then reconnecting. This should immediately invoke CPD. If not then try telling Android to forget the ssid. Then reconnect. If it does not work then, there must be some issue with CPD on that device.

**Comment by kerematam** [comment] 2016-11-27 16:35
Any suggestion for Nodogsplash equivalent Captive Portal software which can handle SSL requests and return 302? Maybe some kind of packet software which includes light weight DNS and https server inside only serve for this purpose.

Also I wonder if SDN approach can be successful? OpenWrt supports OpenFlow, so a SDN controller attached to an AP can solve this?

**Comment by vidarak** [comment] 2016-11-27 16:37
We went with MikroTik RouterOS on virtual machines... and some physical appliances shortly after I started this thread. Have been very satisfied with their reliability.

**Comment by kerematam** [comment] 2016-11-27 16:53
@vidarak So you run virtual RouterOS on PC attached to an OpenWRT APs to handle captive portal?

**Comment by vidarak** [comment] 2016-11-27 17:00
We run virtual RouterOS on ESXi servers (where available), and RouterOS on RouterBoards where we don't have local ESXi servers. The RouterOS is the gateway/dhcp server of the VLAN.

We use mostly Cisco APs with multiple SSIDs attached to separate VLANs. Only the guest VLAN has the captive portal.

**Comment by bluewavenet** [comment] 2016-11-27 18:57
@vidarak , it is good that you found a workable solution for your application.
@xewonder , @pmosse I have found the possible problem with Chrome non-repeatable. It should not matter at all what the client has as home page on their browser as the CPD will always do its port 80 request as soon as the client connects to the WiFi of the Hotspot. 
I have learned a lot about this subject since this issue was started. Looking at statistics I have collected from busy public hotspots running NDS, I see an extremely small number of none mobile devices attaching and of those most are Captive Portal Detection (CPD) capable (Windows 7 and above, Mac(any model), a few Chromebooks and a small but increasing number of Linux laptops). The problem, if it exists in the public hotspot environment, is very very small. Even if the client reaches the configured idle timeout or compulsory timeout, the CPD should (normally) kick in within 5 minutes, the default polling interval for CPD.

Is there a genuine environment where this is not enough, given the rapid increase in support for CPD over the past couple of years?

**Comment by rakesh2215** [comment] 2017-04-09 19:50
Hi Folks,
Have you looked at this?
https://github.com/liudf0716/apfree_wifidog
They are claiming https support. Any comments are welcome. I am yet to try this out myself.

**Comment by bluewavenet** [comment] 2017-06-03 15:13
Things have moved on and CPD has matured more and more.
For example the latest versions of the Facebook App now initially try:
http://h.fb.com/
Latest versions of Firefox have a built in and enabled CPD trying http://detectportal.firefox.com/

**Comment by bluewavenet** [comment] 2017-08-17 18:55
I think this was all a combination of mismatching native CPD and Browser CPD that has now been resolved by the various vendors, both OS and Browser.
https redirection is not required in just about all situations where NDS is likely to be employed now that CPD is mature.

**Closed by bluewavenet** 2017-08-17 18:55 UTC
Labels: enhancement

**Comment by dsmh** [comment] 2018-04-05 16:44
This last part:  "https redirection is not required in just about all situations where NDS is likely to be employed now that CPD is mature." Is not true, I've tried NDS with more than 650 phones and non of them got the CPD working, since now, most of the Captive Portal tools support https. 

This Issue should be reopened since NDS is causing several problems in all the networks I manage, by the lack of https support. 

Please fix this!

**Comment by bluewavenet** [comment] 2018-04-05 18:16
CPD is the universally excepted standard by all OSs and (just about) all browsers and I could show you logs from NDS based captive portals showing hundreds of thousands of operating CPDs on mobiles, tablets, laptops and desktops.
Very few captive portals these days capture on port 443 as this generates dire errors on user machines and is totally unnecessary.
You might think captive portals are supporting https whereas in fact they are not, it is the CPD on devices that is doing, in the background, a port 80 request to one of many many special web pages set up specifically for CPD.
CPD was developed initially by Google in the early days of Android and has developed greatly since then and been adopted by everyone.
The three most used CPD urls in use today are:
http://connectivitycheck.gstatic.com/generate_204
http://captive.apple.com/hotspot-detect.html
http://www.msftconnecttest.com/redirect
All CPD implementations have a built in detection URL, depending on vendor and some can be changed from default. 
You are clearly having a problem, so let us know some details of your NDS configuration, typical configurations and the type/versions of the 650 phones. This must be either a peculiar misconfiguration server side or a very specific "corporate" mobile setup.
