### ISSUE TITLE
iOS clients disconnect when screen locked.

### ISSUE THREAD

**Issue by xam41** [nodogsplash/nodogsplash#209] opened 2017-11-09 04:37 UTC
iOS clients (iPhones, iPads, etc.) disconnect from the wifi when the screen locks and automatically reconnect when unlocked after nodogsplash authentication. Below are the logs of this whole process:

`03:48:51 daemon.info hostapd: wlan0: STA a8:86:dd:c3:3f:c4 IEEE 802.11: authenticated`
`03:48:51 daemon.info hostapd: wlan0: STA a8:86:dd:c3:3f:c4 IEEE 802.11: associated (aid 1)`
`03:48:51 daemon.notice hostapd: wlan0: AP-STA-CONNECTED a8:86:dd:c3:3f:c4`
`03:48:55 daemon.info dnsmasq-dhcp[1264]: DHCPDISCOVER(br-lan) a8:86:dd:c3:3f:c4`
`03:48:55 daemon.info dnsmasq-dhcp[1264]: DHCPOFFER(br-lan) 192.168.11.131 a8:86:dd:c3:3f:c4`
`03:48:55 daemon.info dnsmasq-dhcp[1264]: DHCPDISCOVER(br-lan) a8:86:dd:c3:3f:c4`
`03:48:55 daemon.info dnsmasq-dhcp[1264]: DHCPOFFER(br-lan) 192.168.11.131 a8:86:dd:c3:3f:c4`
`03:48:56 daemon.info dnsmasq-dhcp[1264]: DHCPREQUEST(br-lan) 192.168.11.131 a8:86:dd:c3:3f:c4`
`03:48:56 daemon.info dnsmasq-dhcp[1264]: DHCPACK(br-lan) 192.168.11.131 a8:86:dd:c3:3f:c4`
`03:48:58 daemon.notice nodogsplash[851]: Adding 192.168.11.131 a8:86:dd:c3:3f:c4 token 2ce82758 to client list`
`03:49:04 daemon.notice nodogsplash[851]: Authenticating 192.168.11.131 a8:86:dd:c3:3f:c4`
`03:49:20 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED a8:86:dd:c3:3f:c4`
`03:49:20 daemon.info hostapd: wlan0: STA a8:86:dd:c3:3f:c4 IEEE 802.11: disassociated`
`03:49:21 daemon.info hostapd: wlan0: STA a8:86:dd:c3:3f:c4 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)`
`03:49:43 daemon.info hostapd: wlan0: STA a8:86:dd:c3:3f:c4 IEEE 802.11: authenticated`
`03:49:43 daemon.info hostapd: wlan0: STA a8:86:dd:c3:3f:c4 IEEE 802.11: associated (aid 1)`
`03:49:43 daemon.notice hostapd: wlan0: AP-STA-CONNECTED a8:86:dd:c3:3f:c4`
`03:49:43 daemon.info dnsmasq-dhcp[1264]: DHCPREQUEST(br-lan) 192.168.11.131 a8:86:dd:c3:3f:c4`
`03:49:43 daemon.info dnsmasq-dhcp[1264]: DHCPACK(br-lan) 192.168.11.131 a8:86:dd:c3:3f:c4`

At '03:49:20' the wifi disconnects from the device when screen is locked and at '03:49:43' it reconnects automatically when the screen is unlocked. I have tried _disassoc_low_ack_ and other timeout settings in the wireless config but it has no effect.

Everything works fine with all the same settings if I do not use nodogsplash.

While debugging I found an interesting case. Once authenticated through nodogsplash, if I disconnect the device from the wifi, then hit 'Forget This Network' and then reconnect to the wifi, everything works fine. The device does not disconnect when the screen is locked. Could this be because the device is already authenticated in nodogsplash and has access to the internet so whatever calls iOS makes to Apple's domains (captive.apple.com, apple.com, etc.) all return the correct results?

Perhaps, iOS devices assume that the SSID with authenticated nodogsplash does not have internet access so it just disconnects when the device locks? And once you forget the network and reconnect, since now you are already authenticated and all of Apple's domains return fine, the device believes the SSID has internet and does not disconnect when locked.

I'm using LEDE with nodogsplash - 1.0.2-1. I've also tried v2, it had the exact same outcome.

I've been at this for several days and would love to get to the bottom of this. I would appreciate any help.

**Comment by bluewavenet** [comment] 2017-11-09 10:38
The logs you posted show everything working as it should.
Depending on setup of your smart device, the screen lock may well switch off wifi to save power. This is normal and totally a function of the OS on the device and its setup options.

However I suspect you are seeing a CPD (Captive Portal Detection) loop on your Apple device. This can happen on Android and Windows mobile too and is a deadlock between Network Manager and the CPD and is purely a function of the smart device OS and nothing to do with the functioning of the Captive Portal (NDS in this case).

It happens when the CPD is served the splash page but the client does not authenticate, then the power saving kicks in and switches off the smart device's wifi. At this point the CPD will be waiting. when the WiFi comes back on and reconnects to the NDS wifi the Network Manager sees the CPD has been waiting and assumes failure so disconnects again to try and find an ssid that connects to the internet. 

At this point you may see a wifi symbol with a question mark in your status line, depending on OS and OS version. This whole sequence is a bug, sort of, in Wifi management in smart phones. 

Perhaps not so much a bug but more of a contention between the roaming function of Network Manager and the CPD with attempts to make everything automatic.

If a user finds your NDS wifi and connects, then authenticates then all is well even if the wifi is switched off then back on again, as CPD is not left waiting and not invoked again either as the device is authenticated.

If they find your network and connect to it but do nothing, with the power saving coming on and switching off the wifi, then the problem occurs. 

There is nothing we can do on the NDS side and this is an issue with any form of Captive Portal.
However, my experience of running a number of very busy Public Hotspots shows almost zero complaints from users. This is because if they really want to connect to something they try another ssid or try what you did and "forget" and reconnect or even reset their device. This resets any waiting CPD and all is good again.

CPD has been a defacto standard independently developed by each vendor (often closed source) and is still developing, but now at a much faster rate as CPD has been implemented in all  non embedded Linux distros as well as many browsers. 

Cutting a long story short, there is nothing we can do other than reporting as a bug to Apple, Google, MS etc. However as I said, it is not much of a problem in the real world on busy hotspot sites and reports of this are very few so little is done as fixing this could so easily break other automated functions like roaming.

**Comment by xam41** [comment] 2017-11-09 21:54
> It happens when the CPD is served the splash page but the client does not authenticate, then the power saving kicks in and switches off the smart device's wifi. At this point the CPD will be waiting. when the WiFi comes back on and reconnects to the NDS wifi the Network Manager sees the CPD has been waiting and assumes failure so disconnects again to try and find an ssid that connects to the internet.

>If they find your network and connect to it but do nothing, with the power saving coming on and switching off the wifi, then the problem occurs.

Actually, the wifi disconnects on screen lock even if the user has authenticated through NDS. For example, in the logs at '03:49:20', the device disconnects even after it is authenticated by NDS at '03:49:04'.

If it helps, I'm using the latest LEDE snapshot for router tp-link wr840n v4. Although, I don't think the router is the issue because the wifi works fine without NDS.

**Comment by bluewavenet** [comment] 2017-11-09 22:10
That is what I said. When the screen locks the wifi turns off so of course it disconnects.
"The logs you posted show everything working as it should.
Depending on setup of your smart device, the screen lock may well switch off wifi to save power. This is normal and totally a function of the OS on the device and its setup options."

**Comment by xam41** [comment] 2017-11-09 22:19
Yes, but this is only happening with NDS wifi. If I do not install NDS, devices do not disconnect from the wifi when the screen locks so it can not be how the device is setup.

**Comment by bluewavenet** [comment] 2017-11-09 22:29
I can replicate your log entries by setting an android device to switch off wifi on screen lock. It switches back on on unlock and reconnects. Android flashes up a notification that the wifi has connected and all is well.
Why is this a problem?
It can be a problem if only preauthenticated when the wifi switches off as I described in my original reply.

**Comment by bluewavenet** [comment] 2017-11-09 22:41
I have just checked the logs of a very busy site running NDS v1. In the last 12 hours there have been 299 authentications, 160 of which were iOS. There were no complaints received in this period. Logread shows many wifi disconnects and reconnects, identical to your logs. This is normal.

Can you explain more what the issue is in your case?

**Comment by xam41** [comment] 2017-11-09 22:59
Sure. I'll describe two scenarios:

1. Wifi without NDS: A device connects to the wifi and has access to the internet. The device's screen is then locked, and after 30 seconds it is unlocked. The wifi is still connected.

2. Wifi with NDS: A device connects to the wifi and the NDS captive portal opens up. The device is authenticated, the captive portal closes and the device has access to the internet. The device's screen is then locked, and after 30 seconds it is unlocked. But now, the wifi is disconnected, and 5-10 seconds later the wifi automatically reconnects.

The 30 seconds is just a rough number, the wifi disconnects immediately after the screen is locked as evident by the logs.

So my issue is that the wifi should never disconnect when the screen is locked since that never happens on regular wifi.

Thanks for being patient with me on this. =)

**Comment by bluewavenet** [comment] 2017-11-09 23:18
When authenticated there is no difference as far as a client is concerned. 
I just tested here. 
Client set to keep wifi on when locked:
NDS running or not client stays connected.
I honestly do not think you are seeing what you think you are seeing. This change in operation of a client just does not happen here.
I only see this if the client goes to sleep.
Switching off wifi is reflected immediately in the router logs. Just as you are seeing but regardless of whether NDS is running or not.
Just to make sure I have also connected an access point to the nds router. I see the same in the logs of the access point. So it is not some strange interaction of NDS with the local wifi.

**Comment by xam41** [comment] 2017-11-09 23:48
Strangely enough, this only happens on iOS devices. It works fine on Android.

Anyway, I'll keep digging on my end and update if I find something.

Thanks! =)

**Comment by bluewavenet** [comment] 2017-11-10 09:06
A bit of research - it seems iOS disconnects permanently from an open wifi when locked, only reconnecting when woken up. ie no connection when not being used.
On a secured wifi it will wake up the wifi occasionally to check for emails or whatever.
No apple devices here today so I cannot test it.

**Comment by bluewavenet** [comment] 2017-11-20 12:09
@xam41 
Found any more on this?

**Comment by bluewavenet** [comment] 2017-11-22 10:48
This seems to be normal function of the current iOS CPD so closing this.

**Closed by bluewavenet** 2017-11-22 10:48 UTC

**Comment by xam41** [comment] 2017-12-23 07:06
I've ordered an enterprise router with Captive Portal capabilities built in. I'll see how iOS behaves with that and update.

**Comment by xam41** [comment] 2017-12-30 17:49
I got the enterprise router (UniFi AP-LR, firmware 3.9.15) and tested its Captive Portal capabilities. 

iOS behaves the same with it as it did with NDS. Seems to be an Apple thing after all. =)

**Comment by bluewavenet** [comment] 2017-12-30 18:50
@xam41
Thanks for the feedback.
I hate to say it but I told you so ;-)

Most people on mobiles these days are desperate to get a connection and the first thing they do is restart their device and that always gets them going at least as far as the stats I have collected are concerned. 
I have done a few tests too and it does seem to be the thing on ios to switch off the wifi when the screen sleeps - if the connection is "open". It will probably change again with the next ios update!

**Comment by NikhMh** [comment] 2018-01-11 10:54
@xam41,

Even I'm facing the same issue with iPhones. I'm using coovachilli for hotspot.
 After authentication, Wifi disconnects from the iPhone device when screen is locked and it reconnects automatically when the screen is unlocked. If I forget the network and connect is back, no disconnections observed.

**Comment by bluewavenet** [comment] 2018-01-11 15:13
I have heard from "insiders" that this was implemented officially to help prevent external attacks on an otherwise sleeping iphone, but unofficially as an upgrade to extend battery life. Probably does both.
There is, however, nothing sensible we can do from the captive portal side.
At some large sites, I can see ios devices dropping the wifi connections as described here but have had no negative feedback, most likely as they are all too pleased to have free wifi available.

**Comment by xam41** [comment] 2018-01-12 00:11
I thought it might be an issue with an "open" wifi connection, but if you connect to an "open" wifi connection that is not running NDS, the iOS device doesn't seem to disconnect when the screen sleeps. 

Also, after authenticating through NDS, then disconnecting from the wifi, forgetting the wifi network and connecting again to the same wifi (captive portal won't show since already authenticated), the iOS device will not disconnect when the screen sleeps.

So there is definitely something going on in iOS.

**Comment by bluewavenet** [comment] 2018-01-13 10:51
I think if it detects an open wifi AND a captive portal you see the issue.

**Comment by NikhMh** [comment] 2018-01-14 06:38
@bluewavenet 
It is the issue with open wifi and captive portal. I think, it is something related to captive portal.
Even if I keep iPhone on charging I'm seeing this issue.
