### ISSUE TITLE
Transparent Proxy on authed users.

### ISSUE THREAD

**Issue by lorenzvg** [nodogsplash/nodogsplash#69] opened 2015-04-19 15:30 UTC
Hello,
is it possible for nodogsplash to redirect authed users to a transparent proxy?
i already saw some patch commited: http://ml.ninux.org/pipermail/nodogsplash/2013-February/000012.html

any progress here?

**Comment by sayuan** [comment] 2015-04-19 16:34
Why don't you insert the redirect rules in the proxy's script?
I think that would be more reasonable.

**Comment by lorenzvg** [comment] 2015-04-19 17:21
Well, all i see is nds allowing port 80 on authed users to the wan interface.
i cant seem to manage to redirect them to the proxy. any hints?

**Comment by sayuan** [comment] 2015-04-19 17:41
Blocking all traffic and Allowing port 80 (also DHCP, DNS) is for pre-authenticated user only.
After the user got authenticated, nodogsplash just do nothing and let packets pass.

Therefore, if you need a transparent proxy for authenticated users, I don't think modifying nodogsplash is a good idea.
You just need an iptables rule and make sure it inserted after nodogsplash fw rules (or add some mark checked):
```
iptables -t nat  -A PREROUTING -p tcp -j REDIRECT --to-ports {port of transparent proxy}
```

**Comment by 4L3Xx** [comment] 2015-07-31 00:33
> Blocking all traffic and allowing port 80 (also DHCP, DNS) is for pre-authenticated user only.
This actually hasn't been working for me, TBH.

**Comment by cloudstm** [comment] 2015-08-24 19:06
Hi,

I'm having the same issue, and I'd like to know if someone were able to solve this problem using a transparent proxy.

**Comment by mwarning** [comment] 2015-08-28 07:09
I hope this project will be replaced by something less buggy. See https://github.com/nodogsplash/nodogsplash/tree/v2

**Comment by bluewavenet** [comment] 2015-08-28 07:47
I'm using version 9.9.9 on both Ubiquity and PCEngines hardware and am finding it very stable on barrier breaker and not encountered any bugs. The preauth blocking on 9.9.8 is broken but fixed in 9.9.9 (mwarning I think). All the hard work is appreciated.
I was considering a caching  transparent proxy running on a second openwrt box, an alix 2d2 with 4GB memory perhaps. Quite cheap hardware but other options out there. Worth a try?

**Comment by cloudstm** [comment] 2015-08-28 13:40
I'm using nodogsplash_0.9_beta9.9.9-6_x86.ipk on openwrt 15.05 running on PCENGINES (alix6f2) with 256MB RAM and 4GB CFCARD.
I need to use nodogsplash with a transparent proxy squid.
NODOGSPLASH doesn't forward traffic port 80 to 3128 (squid port) for authenticated users.
I'm testing users that have authenticated already with command iptables:
iptables -t nat -A PREROUTING -p tcp --source 192.168.2.182 --dport 80 -j REDIRECT --to-port 3128
Where 192.168.2.182 is the user IP and 3128 is the squid port.

But the problem is that this rule I'm having to apply manually for every user and I need this rule to be automatically aplied by the nodogsplash for every authenticated user.

I'm reading this tutorial to change v2 https://github.com/nodogsplash/nodogsplash/tree/v2/openwrt
But when I get to this point: cp -rf nodogsplash/openwrt/nodogsplash package/, it doens't have the directory "nodogsplash/openwrt". Can someone help me with that?

**Comment by mwarning** [comment] 2015-08-28 14:34
@bluewavenet using the latest release is always a good idea. :-)

**Comment by cloudstm** [comment] 2015-09-17 13:12
Hi Guys,
Someone got a workable solution to this problem?

**Comment by mwarning** [comment] 2016-11-27 13:06
@cloudstm: nobody seem to be working on this issue..

**Comment by bluewavenet** [comment] 2016-11-27 13:42
I'm not sure this was ever an issue, more like something on a wish list. 
I have successfully used a transparent caching proxy on the default gateway of the NDS box. Simple and cheap and spreads the cpu load over two boxes.

**Closed** 2017-08-30 21:14 UTC
