### ISSUE TITLE
Raspberry pi Zero . No chain/target/match by that name. 

### ISSUE THREAD

**Issue by david191624** [nodogsplash/nodogsplash#273] opened 2018-08-24 03:59 UTC
I am follow this site to setup captive portal
https://pimylifeup.com/raspberry-pi-captive-portal/

Everything go well on Access point and bridge setup,  Mobile Wi-Fi can connect to Internet via rapsberry access-point.

After i follow the instruction Install nodogsplash , nodogsplash cannot work well  , system show
 No chain/target/match by that name.

No chain/target/match by that name
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.

Any one can help ??

iptables -t mangle -v -n -L
Chain PREROUTING (policy ACCEPT 34 packets, 5830 bytes)
 pkts bytes target     prot opt in     out     source               destination
   26  5294 ndsOUT     all  --  br0    *       0.0.0.0/0            0.0.0.0/0
   26  5294 ndsBLK     all  --  br0    *       0.0.0.0/0            0.0.0.0/0
   26  5294 ndsTRU     all  --  br0    *       0.0.0.0/0            0.0.0.0/0
   34  5830 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            MARK or 0x10000

Chain INPUT (policy ACCEPT 34 packets, 5830 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 22 packets, 1528 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 22 packets, 1528 bytes)
 pkts bytes target     prot opt in     out     source               destination
   14   992 ndsINC     all  --  *      br0     0.0.0.0/0            0.0.0.0/0

Chain ndsBLK (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain ndsINC (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain ndsOUT (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain ndsTRU (1 references)
 pkts bytes target     prot opt in     out     source               destination

**Comment by bluewavenet** [comment] 2018-08-24 09:01
It would be useful if you stated what OS and NDS versions you are using.
The tutorial you have followed is very outdated.
#249 might be worth reading.

**Comment by david191624** [comment] 2018-08-27 05:44
It's work fine when i change the NDS to version 1 

git checkout v1

But it doesn't work when i use the latest version NDS Version 3.1, below is my raspbian version. Any one have solution ?

root@raspberrypi:/home/pi# sudo nodogsplash
root@raspberrypi:/home/pi# cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
root@raspberrypi:/home/pi#

**Comment by bluewavenet** [comment] 2018-08-27 07:54
I think this is due to your iptables version.
NDS up to v1.0.1 requires iptables version 1.4.21 or less
NDS v1.0.2 and above requires iptables version 1.4.21 or above
See #180

**Comment by mwarning** [comment] 2018-08-27 08:31
@david191624 can you update iptables?

**Comment by mwarning** [comment] 2018-08-27 08:32
@bluewavenet we could try to backport old iptables support, or add a iptables version check to issues an error if iptables is too old...

**Comment by bluewavenet** [comment] 2018-08-27 08:54
The latest version of Stretch is 9.5, this may well have a more up to date kernel and iptables.
(iptables is kernel specific)

**Comment by bluewavenet** [comment] 2018-08-27 08:59
@mwarning 
Add a Build-Depends: for iptables in:
https://github.com/nodogsplash/nodogsplash/blob/master/debian/control
?

**Comment by mwarning** [comment] 2018-08-27 09:04
@bluewavenet I think we can easily add support for old iptables.

**Comment by bluewavenet** [comment] 2018-08-27 09:09
Stretch 9.5, the current version, is kernel 4.9 so will be iptables 1.6x

**Comment by mwarning** [comment] 2018-08-27 09:17
yes, that would also be a solution then. :)

**Comment by bluewavenet** [comment] 2018-08-27 09:39
@david191624 
Show us the output of:
iptables -V
and
uname -r

**Comment by bluewavenet** [comment] 2018-08-27 09:50
Personally, I think I would try this:
https://downloads.lede-project.org/releases/18.06.1/targets/brcm2708/bcm2708/

**Comment by mwarning** [comment] 2018-08-27 10:48
I've tested NDS v1 on a raspi, I get the same error with iptables 1.4.21.

@bluewavenet you mean https://downloads.openwrt.org/releases/18.06.1/targets/brcm2708/bcm2708/ ;-)

**Comment by david191624** [comment] 2018-08-27 10:54
Thx all, let me try tomorrow back to school.
By the way, where can found which NDS notables is using, I can't found in official site

**Comment by david191624** [comment] 2018-08-27 10:55
Thx all, let me try tomorrow back to school.
By the way, where can found which NDS iptables is using, I can't found in official site

**Comment by bluewavenet** [comment] 2018-08-27 12:00
@mwarning 
tomato tomato
:-D

**Comment by bluewavenet** [comment] 2018-08-27 12:04
@mwarning 
nds v1.0.2?

**Comment by bluewavenet** [comment] 2018-08-27 21:40
People have had this working so something has changed. NDS v1.0.0 has not so that leaves Raspian I guess.
Out of sheer badness i installed 1.0.0 on OpenWrt 17.01.4 and it gives no errors but does not splash. Expected of course. It still runs on 15.05.1

**Comment by mwarning** [comment] 2018-08-28 00:47
I will test stretch next.

**Comment by bluewavenet** [comment] 2018-08-28 09:33
This is giving me a brain itch. I feel I know what is wrong - but can't remember....

**Comment by mwarning** [comment] 2018-08-28 14:04
The problem is probably that the kernel has no mark support:

```
pi@raspberrypi:~ $ cat /proc/config.gz | gunzip | grep MARK
# CONFIG_NETWORK_SECMARK is not set
# CONFIG_NF_CONNTRACK_MARK is not set
# CONFIG_NETFILTER_XT_MARK is not set
# CONFIG_NETFILTER_XT_CONNMARK is not set
# CONFIG_NETFILTER_XT_TARGET_CONNMARK is not set
# CONFIG_NETFILTER_XT_TARGET_HMARK is not set
# CONFIG_NETFILTER_XT_TARGET_MARK is not set
# CONFIG_NETFILTER_XT_MATCH_CONNMARK is not set
# CONFIG_NETFILTER_XT_MATCH_MARK is not set
# CONFIG_TRACEPOINT_BENCHMARK is not set
```

**Comment by bluewavenet** [comment] 2018-08-28 16:07
iptables-mod-conntrack-extra and iptables-mod-ipopt
That's what is itching!

**Comment by mwarning** [comment] 2018-08-28 16:34
I already had libnetfilter-conntrack3 installed manually. But I cannot find iptables-mod-conntrack-extra, iptables-mod-ipopt or similar packages.

@david191624 can you check if there are packages available on your system. And if they are, if they fix your problem.

**Comment by mwarning** [comment] 2018-08-30 09:29
@david191624 can you show us the output of `cat /proc/config.gz | gunzip | grep MARK` on your raspi? I only have a simulated one using qemu. So your output might be different compared to mine.

**Comment by bluewavenet** [comment] 2018-09-24 14:41
This seems to be a Raspberrian-Iptables issue rather than a problem with NDS.
Some people seem to be running successfully, others not. Those not having success are possibly working on academic exercises and have limited experience. There is limited feedback and lack of actual hardware to replicate, so closing for now.

**Closed** 2018-09-24 14:43 UTC

**Comment by bluewavenet** [comment] 2018-10-03 09:37
@mwarning 
xtables-addons required?

**Comment by mwarning** [comment] 2018-10-03 11:46
Not sure. I have to get hold of a raspi and do some testing.

**Comment by bluewavenet** [comment] 2018-10-03 11:55
See my jabber message :-D

**Comment by lxmicro** [comment] 2018-12-02 20:33
In versión 3.2.1 of nodogsplash this resolve the issue:

 apt install xtables-addons-common

**Comment by mwarning** [comment] 2018-12-02 21:07
For me the error does not appear even when xtables-addons-common is not installed (debian 9.4).
On Rasbian, the package does not fix the error.
Either the functionality of the xtables-addons-common package changed or it does not fix the problem.

**Comment by bluewavenet** [comment] 2018-12-03 09:35
Have we established NDS works in Debian but does not work in Raspbian?

**Comment by mwarning** [comment] 2018-12-03 11:33
Two ways:
- compare to raspi setups that work/don't work. (installed packages and kernel build options)
- investigate what specific problem causes the error message

**Comment by bluewavenet** [comment] 2018-12-03 11:48
Is the problem only with Raspian?

**Comment by mwarning** [comment] 2018-12-03 11:52
yes, only Raspian seem to have this problem. But some Raspi installations (also Raspian?) do not have the problem.
