### ISSUE TITLE
memory error in nodogsplash

### ISSUE THREAD

**Issue by stevo01** [nodogsplash/nodogsplash#341] opened 2019-03-12 10:19 UTC
I got error message "*** Error in `nodogsplash': free(): invalid pointer: 0x75108639 ***" several times on my system based on arm. 
I used version with tag "3.2.1" (Latest commit ff4dd48  on 27 Sep 2018) for my investigations.
See attached logfile for details: [nodogsplash_free_error.log](https://github.com/nodogsplash/nodogsplash/files/2956276/nodogsplash_free_error.log)

**Comment by mwarning** [comment] 2019-03-12 15:46
Thank you for reporting the error. This is likely a bug. But I cannot tell what it is caused by.
Can you provide a stack trace?

**Comment by stevo01** [comment] 2019-03-12 16:21
Further investigation shows that: 
- error occur inside function "show_templated_page()" during call of function"free(uptime);" (file http_microhttpd.c line 986). 
- variable uptime is set by call of function "get_uptime_string()"
- get_uptime_string() allocates 64 byte memory with malloc function and calls function "format_duration()"

I guess the handling inside the function "format_duration()" leads to error if timestamp is faulty (to < from).
note: all other calls of function format_duration() using a buffer with 128 instead 64 bytes.

**Comment by stevo01** [comment] 2019-03-12 16:25
> Thank you for reporting the error. This is likely a bug. But I cannot tell what it is caused by.
> Can you provide a stack trace?

I am using an ptp client to syncronize system clock with time server.

**Comment by bluewavenet** [comment] 2019-03-12 16:33
I have had v3.2.1 running continuously on OpenWrt / ARM for a couple of months with no issues.
But then the system clock is correct :-D
What OS are you using @stevo01 ?

**Comment by mwarning** [comment] 2019-03-12 16:43
format_duration does actually take into consideration when to < from: https://github.com/nodogsplash/nodogsplash/blob/3.2.1/src/util.c#L366

btw. the 64 character buffer size should be sufficient.

**Comment by stevo01** [comment] 2019-03-12 16:43
> I have had v3.2.1 running continuously on OpenWrt / ARM for a couple of months with no issues.
> But then the system clock is correct :-D
> What OS are you using @stevo01 ?

OS is based on "yocto krogoth" with Kernel 4.1.x on i.mx6 (32 bit machine). 
I am using a ptp client to synchronise the device with clock master. Unfortunatally the clock master is not working in my test environment. On the other point of view: my setup allows me to reproduce the error :-)

**Comment by bluewavenet** [comment] 2019-03-12 17:22
@stevo01 
Could you let us know more about your configuration? Looking at the log you provided, your IP addressing seems unconventional although that will not cause problems. The NDS gateway address is 192.168.0.28 while the client that is being processed when the error occurred is 192.168.0.1.

NDS does require to be run on a system configured as a router and these addresses possibly imply otherwise. It seems the Captive Portal was triggered by direct access to the NDS gateway address, also indicating an invalid configuration. But again, this should not cause the error you have seen, it would just stop NDS from functioning.

**Comment by stevo01** [comment] 2019-03-13 08:41
> Could you let us know more about your configuration? Looking at the log you provided, your IP addressing seems unconventional although that will not cause problems.

You are right, The setup is just for first test. I plan to realise a wlan access point later on the device and route packages from wlan interface to lte modem interface (similar to the openwrt solution).

note: After I stopped the ptp services, nodogsplash is working like expected. I guess there is a problem if invalid timesstamps are used. I added some debugging infos to find the root cause. see https://github.com/stevo01/nodogsplash/commits/dev-sv for details

**Comment by mwarning** [comment] 2019-03-13 11:23
@does it work when you remove the call to get_uptime_string?

**Comment by stevo01** [comment] 2019-03-13 14:45
> format_duration does actually take into consideration when to < from: https://github.com/nodogsplash/nodogsplash/blob/3.2.1/src/util.c#L366
> 
> btw. the 64 character buffer size should be sufficient.

I made a unit test and found the problem in handling that you mentioned above. If the calculated timespan is negativ in function "format_duration()" than the pointer to the allocated buffer is incremented and returned to caller. The caller calls the free() with invalid pointer...

**Comment by mwarning** [comment] 2019-03-13 15:17
@stevo01 right, should be fixed now. Thanks for the reporting and debugging!

**Closed** 2019-03-13 15:16 UTC
