### ISSUE TITLE
How to change passing variables to FAS

### ISSUE THREAD

**Issue by bawantha** [nodogsplash/nodogsplash#394] opened 2019-07-25 05:10 UTC
Hi 
I'm trying to change passing variables to FAS via query string , I don't know what is entry point of NDS is there any documentation for developers?

**Comment by bluewavenet** [comment] 2019-07-25 10:21
@bawantha 
You can of course make your own version of NDS from the sources.
However in your case the issue is caused by trying to use OpenWrt snapshot for Raspberry Pi and this is currently broken.

The OpenWrt 18.06.4 release for RPi is fine, have you tried this?
Nodogsplash 4.0.0 has not yet been backported to 18.06 packages but the version on snapshot is fully compatible and easy to download and install.

NDS in secure level 1 does not pass the client mac or client token for security reasons.
A knowledgeable user could bypass FAS using the client token, and alternatively clone the mac of an other authenticating device to achieve the same aim.

The client mac is not required for a basic FAS so is not passed in levels 0 and 1.
It is passed along with other information in encrypted form when using secure level 2.

There is no documentation for developers to facilitate source code changes other than reading the inline comments and following the flow of the source code.

There is documentation for developers for using the NDS api's for FAS, PreAuth, BinAuth and Basic Splash.

You have many options, but these are the best to use for your project:

 * Use the released 18.06.4 version of OpenWrt with NDS 4.0.0
 * Wait for Snapshot to be fixed or OpenWrt 19.07.0 to be released
 * Use different hardware (eg a low cost mini router)
 * Write a custom modifications to NDS and compile yourself (this will be insecure, but might not matter if your aim is to provide free Internet with some TOS acceptance/advertising).

**Comment by bawantha** [comment] 2019-07-25 10:28
@bluewavenet I tried with OpenWrt 18.06.4 it is not working for rpi 3 B+ , they ( from OpenWrt forum ) told me 18.06.4 might not work with my pi's  architecture.

**Comment by bluewavenet** [comment] 2019-07-25 17:23
@bawantha 
The problem with snapshot will hopefully be fixed, you will just have to wait.
Another alternative is to use Raspbian instead of Openwrt.
But best of all in my opinion, use one of the modern low cost mini routers eg GL-iNet AR300M or similar. These are designed to be routers, have open source support, are very reliable and best of all, cheaper than an RPi.

**Comment by bawantha** [comment] 2019-07-26 07:20
@bluewavenet  Thank you very much for your support , of course pi is just for poc definetly I need to go with a router,

**Closed** 2019-07-26 07:20 UTC

**Comment by bluewavenet** [comment] 2019-08-11 13:22
@bawantha 
Everything is now fixed on ~Snapshot - In case you have not already noticed :-D
You should now be able to install NDS 4.0.1, php and node!
