### ISSUE TITLE
ndslog.log empty with login_option_enabled 1

### ISSUE THREAD

**Issue by FRHOME** [nodogsplash/nodogsplash#505] opened 2020-01-22 16:44 UTC
Hi,
All in the title. With the option **login_option_enabled 1** and a succesfull Name/Email login, my file ndslog.log is still empty with the text:

"mercredi 22 janvier 2020, 17:31:31 (UTC+0100), New log file created"

Thanks in advance !

**Comment by bluewavenet** [comment] 2020-01-22 18:59
@FRHOME 
Could you please let me know the following:
 1. Your version of NoDogSplash (NDS)
 2. Your Hardware
 3. The operating system and version you are using

The latest release version of NDS is 4.4.0
From memory, an early version of login.sh failed to write its logs. This has been fixed for some time but possibly this is the one you have.

I just tested 4.4.0 here and it works.

**Comment by FRHOME** [comment] 2020-01-23 10:12
@bluewavenet 

1. Version 4.4.0
2. Raspberry 3 B+
3. Raspbian Buster Lite 

NDS working under a RasAP installation. Everything works except the logs. For testing, I set chmod -R 777 on /tmp

**Comment by bluewavenet** [comment] 2020-01-24 14:07
@FRHOME 
Try changing the first line of /usr/lib/nodogsplash/login.sh
from:
`#!/bin/sh`
to
`#!/bin/bash`
and let me know if this fixes the problem.
There is raspbian/debian specific issue caused by the fact that OpenWrt defaults to ash shell, whereas raspbian/debian defaults to a full posix compliant implementation of sh.

**Comment by FRHOME** [comment] 2020-01-24 19:10
@bluewavenet 
I'm already with bash interpretation

**Comment by bluewavenet** [comment] 2020-01-24 20:09
@FRHOME
You have already changed the first line of /usr/lib/nodogsplash/login.sh ?

**Comment by FRHOME** [comment] 2020-01-25 18:55
@bluewavenet 
I didnt change anything, the first line of login.sh was already with bash

**Comment by bluewavenet** [comment] 2020-01-25 21:04
@FRHOME 

>  I didnt change anything, the first line of login.sh was already with bash

In that case you are actually using master "snapshot" 4.4.1beta.
This is not a release and has changed a few times in the last week or so.

> "mercredi 22 janvier 2020, 17:31:31 (UTC+0100), New log file created"

This shows that login.sh is able to create and write to the log file.
Try again then look in the system log for something like:
`PreAuth - log file too big, please archive contents`

It may be a possible bash compatibility issue.

**Comment by bluewavenet** [comment] 2020-01-27 16:51
@FRHOME 
The problem was scripting errors in login.sh. This only seemed to effect Raspbian and OpenWrt19.07.0.
PR #511 fixes (I hope!) and is now merged into master.

I would appreciate it if you could test this.
Download the source files for master, then copy demo-preauth.sh to /usr/lib/nodogsplash.
Delete /usr/lib/nodogsplash/login.sh and rename demo-preauth.sh to login.sh
Finally check that login.sh is executable.

**Comment by FRHOME** [comment] 2020-01-28 16:10
@bluewavenet 
I copied/pasted the login.sh of the master 4.4.0 and I still have the same issue.

**Comment by bluewavenet** [comment] 2020-01-29 01:08
@FRHOME 
Master is v4.4.1beta. Perhaps you copied the wrong one.

You have to copy demo-preauth.sh and rename to login.sh

You can download the source files for master here:
https://github.com/nodogsplash/nodogsplash/archive/master.zip

> Download the source files for master, then copy demo-preauth.sh to /usr/lib/nodogsplash.
> Delete /usr/lib/nodogsplash/login.sh and rename demo-preauth.sh to login.sh
> Finally check that login.sh is executable.

**Comment by bluewavenet** [comment] 2020-01-29 01:34
1. Download the source files for master,
https://github.com/nodogsplash/nodogsplash/archive/master.zip
then copy forward_authentication_service/PreAuth/demo-preauth.sh to /usr/lib/nodogsplash

 2. Delete /usr/lib/nodogsplash/login.sh and rename demo-preauth.sh to login.sh

 3. Edit the new login.sh, changing the first line from
`#!/bin/sh`
to
`#!/bin/bash`

 4. Copy forward_authentication_service/libs/get_client_interface.sh to /usr/lib/nodogsplash

 5. Change the first line of get_client_interface.sh from
`#!/bin/sh`
to
`#!/bin/bash`

 6. Finally check that both login.sh and get_client_interface.sh are executable.

**Comment by bluewavenet** [comment] 2020-01-29 01:42
or a simpler solution - recompile from a NEWLY downloaded master.
(too tired :D)

**Closed** 2020-01-30 09:58 UTC

**Comment by FRHOME** [comment] 2020-01-30 11:23
I have downloaded https://github.com/nodogsplash/nodogsplash/archive/master.zip and delete / recompile everything... still the same issue

**Comment by FRHOME** [comment] 2020-01-30 12:10
i did : 
```
sizeratio=1

        if [ $sizeratio=1 ]; then
                htmlentitydecode $username
                userinfo="username=$entitydecoded, emailAddress=$emailaddr"
                clientinfo="macaddress=$clientmac, clientzone=$client_zone, useragent=$user_agent"
                echo "$datetime, $userinfo, $clientinfo" >> $logfile
```

And now its working.
The issue come from `sizeratio=$(($available/$filesize))`

**Comment by bluewavenet** [comment] 2020-01-30 12:44
@FRHOME 
Thanks. Yes I found the actual problem - it only occurs with some operating systems/versions and not others.
$available should be the available free space on /tmp.
This line has fixed the issue on all the OS I have been able to test on (unfortunately I do not have anything I can run Raspbian on):
`available=$(df |grep /tmp | awk -F ' ' '$6=="/tmp"{print $4}')`

Could you post the output of df | grep "/tmp" please?

**Comment by FRHOME** [comment] 2020-01-30 12:57
No output with this `df`
`available=$(df |grep /tmp | awk -F ' ' '$6=="/tmp"{print $4}')` is not working :'(

**Comment by bluewavenet** [comment] 2020-01-30 13:06
`df` gives no output?
`sudo df` maybe?
What does Raspbian have to give you storage space?

**Comment by FRHOME** [comment] 2020-01-30 13:07
```
/dev/root           30391116 1614980   27505936   6% /
devtmpfs              469540       0     469540   0% /dev
tmpfs                 474148       0     474148   0% /dev/shm
tmpfs                 474148    6356     467792   2% /run
tmpfs                   5120       4       5116   1% /run/lock
tmpfs                 474148       0     474148   0% /sys/fs/cgroup
/dev/mmcblk0p1        258095   54393     203703  22% /boot
tmpfs                  94828       0      94828   0% /run/user/1000
```

**Comment by bluewavenet** [comment] 2020-01-30 14:41
There is no /tmp
Where does it write the log file?

**Comment by FRHOME** [comment] 2020-01-30 14:57
Yes there a /tmp but the grep is empty in this folder. Well, df | grep /tmp returns nothing

**Comment by privet971** [comment] 2020-02-02 16:34
For Raspbian  :
available=$(df | grep root | awk '{print $4}')

**Comment by bluewavenet** [comment] 2020-02-02 16:59
@privet971 
Would /run be better?
`available=$(df | grep root | awk '{print $4}')

**Comment by bluewavenet** [comment] 2020-02-02 17:06
@privet971 
Actually I meant:
available=$(df |grep /run | awk -F ' ' '$6=="/run"{print $4}')

**Comment by privet971** [comment] 2020-02-02 17:43
@bluewavenet 
No, I don't think so,  because the tmp folder is on the root partition.

moreover, I think log file sould be in the log folder and in his own directory like /var/log/nds  because a each reboot the tmp directory is emptied so logs too.

**Comment by bluewavenet** [comment] 2020-02-02 18:53
@privet971 
I don't have anything to run Raspbian on, so much appreciate your input.

I am coming from the OpenWrt world where /tmp is tmpfs (in ram) and obviously is cleared on reboot.

This location is deliberate for a default script that would otherwise ultimately damage flash storage. Of course in a "production" system you will want to have non volatile logs, probably best on a usb stick!

The login.sh script should probably have an easily customisable variable defining the log file location, somewhere at the beginning to make customisation simple.

I saw from @FRHOME 's df output that /run is tmpfs, hence  my suggestion.
Your thoughts?
