### ISSUE TITLE
Problems with FAS

### ISSUE THREAD

**Issue by Zhenyoker** [nodogsplash/nodogsplash#346] opened 2019-04-01 09:15 UTC
Did everything according to the instructions, can't even run an example. What have I done wrong? openwrt, nodogsplash 3.2.1, uhttpd, php7
![Screenshot from 2019-04-01 11-09-46](https://user-images.githubusercontent.com/25462709/55316769-1c892900-543d-11e9-9005-d452aa53e7a4.png)

**Comment by mwarning** [comment] 2019-04-01 09:19
Please try a gateway name without spaces.

**Comment by bluewavenet** [comment] 2019-04-01 10:36
@Zhenyoker 
What OS are you using and could you post your nodogsplash and uhttpd configuration?
Spaces in the gatewayname are fine.
@mwarning Good point though, gatewayname should be urlencoded here I think.

**Comment by bluewavenet** [comment] 2019-04-01 10:58
@Zhenyoker 
Try the following to test uhttpd is working:
Stop nds (service nodogsplash stop)
In your browser enter  the fas url (192.168.1.1/nodog/fas.php)
If uhttpd is working correctly you should get the login page with an error saying

> ERROR! Incomplete data passed from NDS

**Comment by Zhenyoker** [comment] 2019-04-01 11:21
> @Zhenyoker
> Try the following to test uhttpd is working:
> Stop nds (service nodogsplash stop)
> In your browser enter the fas url (192.168.1.1/nodog/fas.php)
> If uhttpd is working correctly you should get the login page with an error saying
> 
> > ERROR! Incomplete data passed from NDS

Thanks for the quick response! 

>  If uhttpd is working correctly you should get the login page with an error saying

I checked. Everything is working. But the problem did not dare. removing the space did not help

> What OS version are you using and could you post your nodogsplash and uhttpd configuration?

OpenWrt 18.06.2

[uhttpd.txt](https://github.com/nodogsplash/nodogsplash/files/3029072/uhttpd.txt)
[nodogsplash.txt](https://github.com/nodogsplash/nodogsplash/files/3029073/nodogsplash.txt)

**Comment by bluewavenet** [comment] 2019-04-01 11:59
@Zhenyoker 
On your client machine, is the OS CPD triggering NDS redirection or are you typing in some url?

It looks like the browser is in a redirect loop for some reason.
I am unable to reproduce the problem here with a similar configuration so need to know exactly what you do to get the error.

**Comment by Zhenyoker** [comment] 2019-04-01 12:52
Reinstalled Openwrt and all other programs. Problem still exists. I connect from the phone via wifi, and automatically get on this page with an error. The same thing happens if I enter 192.168.1.1 in the browser and on the phone and on the computer via cable. Could it be that the "luci" is also on port 80?

**Comment by Zhenyoker** [comment] 2019-04-01 12:58
full content of the address bar of the page with an error:

http://192.168.1.1/nodog/fas.php?authaction=http://192.168.1.1:2050/nodogsplash_auth/?clientip=192.168.1.202&gatewayname=OpenWrt%20Nodogsplash&tok=4c8d2e2b&redir=http%3a%2f%2f192.168.1.1%2fnodog%2ffas.php%3fredir%3dhttp%3a%2f%2f192.168.1.1%2fnodog%2ffas.php%3fredir%3dhttp%3a%2f%2f192.168.1.1%2fnodog%2ffas.php%3fredir%3dhttp%3a%2f%2f192.168.1.1%2fnodog%2ffas.php%3fredir%3dhttp%3a%2f%2f192.168.1.1%2fnodog%2ffas.php%3fredir%3dhttp%3a%2f%2f192.168.1.1%2fnodog%2ffas.php%3fredir%3dhttp%3a%2f%2f192.168.1.1%2fnodog%2ffas.php%3fredir%3dhttp%3a%2f%2f192.168.1.1%2fnodog%2ffas.php%3fredir%3dhttp%3a%2f%2f192.168.1.1%2fnodog%2ffas.php%3fredir%3dhttp%3a%2f%2f192.168.1.1%2fnodog%2ffas.php%3fredir%3dhttp%3a%2f%2f192.168.1.1%2fnodog%2ffas.php%3fredir%3dhttp%3a%2f%2f192.168.1.1%2fnodog%2ffas.php%3fredir%3dhttp%3a%2f%2f192.168.1.1%2fnodog%2ffas.php%3fredir%3dhttp%3a%2f%2f192.168.1.1%2fnodog%2ffas.php%3fredir%3dhttp%3a%2f%2f192.168.1.1%2fnodog%2ffas.php%3fredir%3dhttp%3a%2f%2f192.168.1.1%2fnodog%2ffas.php%3fredir%3dhttp%3a%2f%2f192.168.1.1%2fnodog%2ffas.php%3fredir%3dhttp%3a%2f%2f192.168.1.1%2fnodog%2ffas.php%3fredir%3dhttp%3a%2f%2f192.168.1.1%2fnodog%2ffas.php%3fredir%3dhttp%3a%2f%2f192.168.1.1%2fcgi-bin%2fluci

**Comment by bluewavenet** [comment] 2019-04-01 13:12
@Zhenyoker 
On your client machine/mobile, is the OS CPD triggering NDS redirection or are you typing in a url?

Yes, by default, luci is on port 80 and can coexist with fas on the same port as fas is in a different directory accessed by a different url.

It looks like the browser is in a redirect loop as your initial request looks like it was for 192.168.1.1 (on port 80) which in turn redirects to luci.

CPD on all devices and most browsers will attempt to access an external detection url on port 80 and will trigger NDS. 

If CPD is not triggering NDS, this is usually a result of DNS being unable to resolve the CPD url as there is no Internet connection.

**Comment by Zhenyoker** [comment] 2019-04-01 13:36
triggering NDS redirection. Internet on the router works. if turn off NDS web pages open. if NDS is enabled, then this page with an error appears automatically when connected. google.com for example does not work.

**Comment by bluewavenet** [comment] 2019-04-01 14:51
@Zhenyoker 
I have just reflashed a router with openwrt 18.06.2, installed NDS 3.2.1, the demo fas files and configured as in the documentation, I have an ethernet Internet connection to the router and WiFi for client connections. It worked perfectly first time.
I am unable to replicate your problem unfortunately.

What is the WAN address of your NDS router?

In your address bar content post, you seem to have manually entered 192.168.1.1 into the browser to trigger a response. This will not work, instead the response should be automatic. The query string will normally show a "redir" as a detection url, something like:
http://connectivitycheck.gstatic.com/generate_204
or
http://captive.apple.com/hotspot-detect.html
for example. Are you seeing this at any time?

**Comment by bluewavenet** [comment] 2019-04-04 13:30
PR #347 may prevent this issue from happening - not sure.
@Zhenyoker Closing this for now, do please reply if you are still having problems.

**Closed by bluewavenet** 2019-04-04 13:30 UTC

**Comment by Zhenyoker** [comment] 2019-04-04 13:53
Perhaps this is due to the fact that I get the Internet via wifi, and not via Ethernet? I can only check tomorrow
