### ISSUE TITLE
visit https site from desktop browser

### ISSUE THREAD

**Issue by laoshaw** [nodogsplash/nodogsplash#140] opened 2016-09-24 13:06 UTC
it took a very long time(a few minutes) before I see the nodogsplash page when I visit a https site, if I visit a http site the splash page will pop up immediately. mobile phones can detect the portal and try a http to get the splash page, not the case for Desktops which has no portal-detection built-in.

is it possible to get libmicrohttpd/ssl support done at nodogsplash(installing CA is fine)?

**Comment by mwarning** [comment] 2016-09-24 15:54
Afaik, nobody tried that yet.

**Comment by bluewavenet** [comment] 2016-09-24 20:33
In fact Windows 8 and above, OSx and Linux all support Captive Portal Detection. Latest versions seem to have it enabled by default so the problem is becoming less of a problem daily. Also I am monitoring the logs of some very busy public hotspots and find 99.9% of all clients are running iOS, Android, or Windows Mobile, making this problem even less of a problem. Having said all that it would be nice to have a solution, but in my opinion not really necessary for most applications.

**Comment by laoshaw** [comment] 2016-09-25 00:16
I'm using ubuntu and yes https will bring up the splash page, but it took minutes, if you visit a http page the splash page came up immediately, so the captive-portal-detection is not working as good as mobile devices at least.

**Comment by bluewavenet** [comment] 2016-09-26 11:54
Strange, https will *not* bring up the splash page in any circumstances as Captive Portal Detection (lets call it CPD) as it is designed to use its own http port 80 request. 

On Linux CPD is built into Networkmanager. Different distributions use their own url but all of them are designed to return 204 "no content" return code. This signals to the CPD that a valid Internet connection is present. If the CPD receives anything other than 204 it will assume a splash page, if it receives nothing it will assume no connection to the internet. All this is done on port 80.

The configuration is in the NetworkManager.conf file, found usually in /etc/networkmanager or thereabouts.
It will be in the [connectivity] section.

in OpenSuse Leap it is:
[connectivity]
uri=http://conncheck.opensuse.org
response=NetworkManager is online
interval=300

In Debian it is:
[connectivity]
uri=http://network-test.debian.org/nm
response=NetworkManager is online
interval=300

It will be similar in Ubuntu.

Note the interval defaults to 300 seconds. On first connecting to the WiFi the CPD will try the configured URL. Then it will retry at 300 second intervals. 

What you may be seeing is the following sequence:
1. You are already connected to the Wifi but not logged in
2. You open your browser and try an https site.
3. NodogSplash ignores you
4. The timing interval expires and the CPD kicks in, receives something other than 204 from NDS and pops up its browser to display the NDS splash page.

Obviously this can take up to 5 minutes (300 seconds) with the default NetworkManager config.

What NetworkManager settings do you have?

**Comment by lynxis** [comment] 2017-01-19 14:16
@laoshaw which version of nodogsplash are you using?

**Closed** 2017-08-30 20:26 UTC
Labels: waiting for answer
